server:
  port: 8081
  http2.enabled: true
  compression.enabled: true
  netty.h2c-max-content-length: 1MB
management:
  endpoints.web.exposure.include: health, prometheus
  tracing:
    enabled: false
    sampling.probability: 1.0

spring:
  webflux:
    problemdetails:
      enabled: true
  application:
    name: CarService
logging.level.root: TRACE
application:
  include-error-causing-element:
    enabled: true
    included-classes:
      - io.lukas_krickl.car_service.model.Car

  car-repository:
    work-factor: 100ns
    mock-generator:
      amount-of-cars: 1000
