server:
  port: 8081
  http2.enabled: true
  ssl:
    enable: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeit
    enabled-protocols: TLSv1.3


management:
  endpoints.web.exposure.include: health, prometheus
  tracing:
    enabled: false
    sampling.probability: 1.0

spring:
  webflux:
    problemdetails:
      enabled: true
  application:
    name: CarService
logging.level:
  root: INFO
  reactor.netty.http.client.HttpClientOperations: debug
  reactor.netty.http.server.HttpServerOperations: debug
  #reactor.netty.http.client.h2: debug
  #reactor.netty.http.server.h2: debug
  reactor.netty.http.server.AccessLog: INFO

application:
  include-error-causing-element:
    enabled: true
    included-classes:
      - io.lukas_krickl.car_service.model.Car

  car-repository:
    work-factor: 100ns
    mock-generator:
      amount-of-cars: 1000
