server:
  port: 8081

spring:
  webflux:
    problemdetails:
      enabled: true
  application:
    name: CarService
logging:
  level:
    root: INFO

application:
  include-error-causing-element:
    enabled: true
    included-classes:
      - io.lukas_krickl.car_service.model.Car

  car-repository:
    work-factor: 100ns
    mock-generator:
      amount-of-cars: 1000
