server:
  port: 8080
  http2.enabled: true
management:
  endpoints.web.exposure.include: health, prometheus
  tracing:
    enabled: false
    sampling.probability: 1.0

spring:
  webflux:
    problemdetails:
      enabled: true
  application:
    name: ClusteringService

logging.level:
  root: debug
  reactor.netty.http.client.HttpClientOperations: trace
  reactor.netty.http.server.HttpServerOperations: trace
  reactor.netty.http.client.h2: debug
  reactor.netty.http.server.h2: debug

application:
  clustering:
    min-points: 2
    eps: 2000
  clients:
    car-service:
      base-url: http://localhost:8081


