global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: 'apps'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8081','host.docker.internal:8080']
    - job_name: 'tempo'
      static_configs:
        - targets: ['host.docker.internal:3200']
